type=item
items=minecraft:light_gray_stained_glass_pane
model=item/skyblock/gui/gloves_slot.json
nbt.display.Name=ipattern:*Empty Equipment Slot*
nbt.display.Lore=ipattern:*> Gloves*> Bracelet*
weight=2