type=item
items=minecraft:player_head
model=item/skyblock/item/fishing/volcanic_stonefish.json
nbt.display.Name=ipattern:*volcanic stonefish*
nbt.display.Lore=ipattern:*Diamond*Gold*Silver*Bronze*