type=item
items=minecraft:prismarine_shard
model=item/skyblock/item/enchantedbook/attribute_shard_red.json
nbt.display.Lore=ipattern:*\u2716*
nbt.ExtraAttributes.id=ipattern:*attribute_shard*
weight=10