set-option global tabstop 4
set-option global indentwidth 0

set-option global scrolloff 3,6

add-highlighter global/ wrap -word -marker "⌙"
add-highlighter global/ show-whitespaces -tab " " -lf " "
add-highlighter global/ show-matching

eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

face global Default default
face global PrimarySelection default,bright-black
face global MenuForeground default,bright-black
face global MenuBackground default
face global Information default
face global MatchingChar +Bbu
face global Whitespace bright-black
face global WrapMarker Whitespace
set global ui_options terminal_assistant=none
