font_family Fira Code Retina
font_features FiraCode-Retina +ss04
font_size 13.0

cursor_shape beam
cursor_beam_thickness 1

sync_to_monitor yes

enable_audio_bell no
visual_bell_duration 0.05
visual_bell_color black

window_padding_width 5
placement_strategy top-left
hide_window_decorations yes
resize_in_steps yes

tab_bar_style powerline
tab_powerline_style slanted

background_opacity 0.75

# BEGIN_KITTY_THEME
# Campbell
include current-theme.conf
# END_KITTY_THEME
