type=item
items=minecraft:player_head
model=item/skyblock/item/potions/blaze_rod_distillate.json
nbt.display.Name=ipattern:*blaze rod distillate*
nbt.display.Lore=ipattern:*Click*to*claim*
weight=1