type=item
items=minecraft:experience_bottle
model=item/skyblock/item/colossal_experience_bottle.json
nbt.display.Name=ipattern:*colossal experience bottle*
nbt.display.Lore=ipattern:*Click*to*view*